export interface VendorRow {
  accountNum: string;
  topGroup: string;
  name: string;
  vendorGroup: string;
  address: string;
  currency: string;
  sumAmount: number;
  generalizedCategory: string;
  category: string;
  additionalServices: string;
}

export interface CategorySummary {
  category: string;
  vendorCount: number;
  totalSpend: number;
  pctOfTotal: number;
}

export interface ParetoSummary {
  totalSpend: number;
  threshold80Pct: number;
  vendorsFor80Pct: number;
  totalVendors: number;
  pctOfVendors: number;
}

export interface DashboardSummary {
  totalSpend: number;
  totalVendors: number;
  totalCategories: number;
  top80PctSpend: number;
  top80PctVendors: number;
  byCategory: CategorySummary[];
  topVendors: VendorRow[];
  pareto: ParetoSummary;
}

export interface VendorListResponse {
  total: number;
  limit: number;
  offset: number;
  vendors: VendorRow[];
}

export interface CategoryDetail {
  category: string;
  vendorCount: number;
  totalSpend: number;
  pctOfTotal: number;
  avgVendorSpend: number;
  rationalizationLever: string;
  topVendors: VendorRow[];
}

export interface CategoryAnalyticsResponse {
  categories: CategoryDetail[];
  totalSpend: number;
  totalVendors: number;
}

export interface ParetoRow {
  rank: number;
  vendorName: string;
  spendAmount: number;
  cumulativeSpend: number;
  cumulativePct: number;
  topGroup: string | null;
}

export interface ParetoAnalysisResponse {
  rows: ParetoRow[];
  summary: ParetoSummary;
}

export interface SavingsOpportunity {
  id: string;
  name: string;
  category: string;
  currentSpend: number;
  estimatedSavingsLow: number;
  estimatedSavingsHigh: number;
  confidence: number;
  lever: string;
  stage: string;
  timeline: string;
  action: string;
}

export interface SavingsOpportunitiesResponse {
  totalIdentifiedSavings: number;
  activeOpportunities: number;
  quickWins: number;
  avgConfidence: number;
  opportunities: SavingsOpportunity[];
}

export const LEVER_COLOR: Record<string, string> = {
  'Aggregate & Rationalize': '#2563eb',
  'Renegotiate & Partner': '#7c3aed',
  'Deep-Dive & Rebid': '#059669',
};

export const LEVER_BG: Record<string, string> = {
  'Aggregate & Rationalize': '#eff6ff',
  'Renegotiate & Partner': '#f5f3ff',
  'Deep-Dive & Rebid': '#f0fdf4',
};

export const STAGE_COLOR: Record<string, string> = {
  'Identified': '#7c3aed',
  'Validated': '#1d4ed8',
  'In Progress': '#b45309',
  'Completed': '#15803d',
};

// ── Strategic Levers panel (computed live by the backend) ──────────────────

export interface StrategicLeverSummary {
  lever: string;
  scopeSpend: number;
  categoryCount: number;
  vendorCount: number;
  exampleCategories: string[];
}

// ── Tunable config edited from the Settings admin page ─────────────────────

export interface SavingsBucket {
  minVendors: number;
  maxVendors: number | null;
  savingsLowPct: number;
  savingsHighPct: number;
  confidence: number;
  stage: string;
  timeline: string;
  action: string;
  identifiedStageWhenVendorsAtLeast: number | null;
}

export interface InsightThresholds {
  quickWinMaxVendors: number;
  quickWinMinSpend: number;
  consolidationLowPct: number;
  consolidationHighPct: number;
}

export interface KpiTargets {
  activeVendorsTarget: string;
}

export interface VendorRationalizationConfig {
  leverAssignments: Record<string, string>;
  savingsBuckets: SavingsBucket[];
  insightThresholds: InsightThresholds;
  kpiTargets: KpiTargets;
  paretoThresholdPct: number;
  chatModelRef: string | null;
}

// ── AI Insights (dashboard cards generated by the configured LLM) ──────────

export interface AiInsight {
  title: string;
  body: string;
  severity: 'high' | 'medium' | 'low' | string;
  iconHint: 'consolidation' | 'risk' | 'quick-win' | 'info' | string;
}

export interface AiInsightsResponse {
  insights: AiInsight[];
  generatedAt: number;
  modelRef: string | null;
  cached: boolean;
}

export const LEVER_OPTIONS = [
  'Aggregate & Rationalize',
  'Renegotiate & Partner',
  'Deep-Dive & Rebid',
] as const;
